export enum CharacterAnimationEnum {
  Death = 'CharacterArmature|Death',
  Duck = 'CharacterArmature|Duck',
  HitReact = 'CharacterArmature|HitReact',
  Idle = 'CharacterArmature|Idle',
  IdleGun = 'CharacterArmature|Idle_Gun',
  Jump = 'CharacterArmature|Jump',
  JumpIdle = 'CharacterArmature|Jump_Idle',
  JumpLand = 'CharacterArmature|Jump_Land',
  No = 'CharacterArmature|No',
  Punch = 'CharacterArmature|Punch',
  Run = 'CharacterArmature|Run',
  RunGun = 'CharacterArmature|Run_Gun',
  RunSlash = 'CharacterArmature|Run_Slash',
  RunStab = 'CharacterArmature|Run_Stab',
  Slash = 'CharacterArmature|Slash',
  Stab = 'CharacterArmature|Stab',
  Walk = 'CharacterArmature|Walk',
  WalkGun = 'CharacterArmature|Walk_Gun',
  Wave = 'CharacterArmature|Wave',
  Yes = 'CharacterArmature|Yes',
}
