export enum SkeletonAnimationEnum {
    Death = 'CharacterArmature|CharacterArmature|CharacterArmature|Death|CharacterArmature|Dea',
    Duck = 'CharacterArmature|CharacterArmature|CharacterArmature|Duck|CharacterArmature|Duck',
    HitReact = 'CharacterArmature|CharacterArmature|CharacterArmature|HitReact|CharacterArmature|',
    Idle = 'CharacterArmature|CharacterArmature|CharacterArmature|Idle|CharacterArmature|Idle',
    Jump_Idlea = 'CharacterArmature|CharacterArmature|CharacterArmature|Jump_Idlea|CharacterArmatur',
    Jump_Idle = 'CharacterArmature|CharacterArmature|CharacterArmature|Jump_Idle|CharacterArmature',
    Jump_Land = 'CharacterArmature|CharacterArmature|CharacterArmature|Jump_Land|CharacterArmature',
    Jump = 'CharacterArmature|CharacterArmature|CharacterArmature|Jump|CharacterArmature|Jump',
    No = 'CharacterArmature|CharacterArmature|CharacterArmature|No|CharacterArmature|No',
    Punch = 'CharacterArmature|CharacterArmature|CharacterArmature|Punch|CharacterArmature|Pun',
    Run = 'CharacterArmature|CharacterArmature|CharacterArmature|Run|CharacterArmature|Run',
    Sword = 'CharacterArmature|CharacterArmature|CharacterArmature|Sword|CharacterArmature|Swo',
    Walk = 'CharacterArmature|CharacterArmature|CharacterArmature|Walk|CharacterArmature|Walk',
    Wave = 'CharacterArmature|CharacterArmature|CharacterArmature|Wave|CharacterArmature|Wave',
    Yes = 'CharacterArmature|CharacterArmature|CharacterArmature|Yes|CharacterArmature|Yes',
}